// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.0
// source: proto/crucible.proto

package cruciblev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxControl_CreateSandbox_FullMethodName    = "/vaos.kernel.crucible.v1.SandboxControl/CreateSandbox"
	SandboxControl_ExecuteCode_FullMethodName      = "/vaos.kernel.crucible.v1.SandboxControl/ExecuteCode"
	SandboxControl_TerminateSandbox_FullMethodName = "/vaos.kernel.crucible.v1.SandboxControl/TerminateSandbox"
	SandboxControl_Heartbeat_FullMethodName        = "/vaos.kernel.crucible.v1.SandboxControl/Heartbeat"
	SandboxControl_ExecuteTask_FullMethodName      = "/vaos.kernel.crucible.v1.SandboxControl/ExecuteTask"
)

// SandboxControlClient is the client API for SandboxControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxControl service for VAS-Crucible communication
type SandboxControlClient interface {
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	ExecuteCode(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	TerminateSandbox(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Legacy: ExecuteTask for backward compatibility
	ExecuteTask(ctx context.Context, in *CrucibleTaskRequest, opts ...grpc.CallOption) (*CrucibleTaskResponse, error)
}

type sandboxControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxControlClient(cc grpc.ClientConnInterface) SandboxControlClient {
	return &sandboxControlClient{cc}
}

func (c *sandboxControlClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxControl_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) ExecuteCode(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, SandboxControl_ExecuteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) TerminateSandbox(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxControl_TerminateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, SandboxControl_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) ExecuteTask(ctx context.Context, in *CrucibleTaskRequest, opts ...grpc.CallOption) (*CrucibleTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrucibleTaskResponse)
	err := c.cc.Invoke(ctx, SandboxControl_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxControlServer is the server API for SandboxControl service.
// All implementations must embed UnimplementedSandboxControlServer
// for forward compatibility.
//
// SandboxControl service for VAS-Crucible communication
type SandboxControlServer interface {
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	ExecuteCode(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	TerminateSandbox(context.Context, *TerminateRequest) (*emptypb.Empty, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Legacy: ExecuteTask for backward compatibility
	ExecuteTask(context.Context, *CrucibleTaskRequest) (*CrucibleTaskResponse, error)
	mustEmbedUnimplementedSandboxControlServer()
}

// UnimplementedSandboxControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxControlServer struct{}

func (UnimplementedSandboxControlServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedSandboxControlServer) ExecuteCode(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCode not implemented")
}
func (UnimplementedSandboxControlServer) TerminateSandbox(context.Context, *TerminateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSandbox not implemented")
}
func (UnimplementedSandboxControlServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSandboxControlServer) ExecuteTask(context.Context, *CrucibleTaskRequest) (*CrucibleTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedSandboxControlServer) mustEmbedUnimplementedSandboxControlServer() {}
func (UnimplementedSandboxControlServer) testEmbeddedByValue()                        {}

// UnsafeSandboxControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxControlServer will
// result in compilation errors.
type UnsafeSandboxControlServer interface {
	mustEmbedUnimplementedSandboxControlServer()
}

func RegisterSandboxControlServer(s grpc.ServiceRegistrar, srv SandboxControlServer) {
	// If the following call panics, it indicates UnimplementedSandboxControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxControl_ServiceDesc, srv)
}

func _SandboxControl_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_ExecuteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).ExecuteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_ExecuteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).ExecuteCode(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_TerminateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).TerminateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_TerminateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).TerminateSandbox(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrucibleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).ExecuteTask(ctx, req.(*CrucibleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxControl_ServiceDesc is the grpc.ServiceDesc for SandboxControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vaos.kernel.crucible.v1.SandboxControl",
	HandlerType: (*SandboxControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _SandboxControl_CreateSandbox_Handler,
		},
		{
			MethodName: "ExecuteCode",
			Handler:    _SandboxControl_ExecuteCode_Handler,
		},
		{
			MethodName: "TerminateSandbox",
			Handler:    _SandboxControl_TerminateSandbox_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _SandboxControl_Heartbeat_Handler,
		},
		{
			MethodName: "ExecuteTask",
			Handler:    _SandboxControl_ExecuteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crucible.proto",
}
