// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: proto/crucible.proto

package cruciblev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create a new sandbox
type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	IntentHash    string                 `protobuf:"bytes,3,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`
	Limits        *ResourceLimits        `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_proto_crucible_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSandboxRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *CreateSandboxRequest) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

func (x *CreateSandboxRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	PtyPath       string                 `protobuf:"bytes,2,opt,name=pty_path,json=ptyPath,proto3" json:"pty_path,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_proto_crucible_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse) GetPtyPath() string {
	if x != nil {
		return x.PtyPath
	}
	return ""
}

func (x *CreateSandboxResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Execute code in a sandbox
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_crucible_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecuteRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_crucible_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Terminate a sandbox
type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_proto_crucible_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{4}
}

func (x *TerminateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *TerminateRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

// Resource limits for sandbox
type ResourceLimits struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuCores       int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb       int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	NetworkEnabled bool                   `protobuf:"varint,3,opt,name=network_enabled,json=networkEnabled,proto3" json:"network_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_proto_crucible_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceLimits) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceLimits) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceLimits) GetNetworkEnabled() bool {
	if x != nil {
		return x.NetworkEnabled
	}
	return false
}

// Heartbeat check
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Jwt           string                 `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_crucible_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *HeartbeatRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	LastSeen      int64                  `protobuf:"varint,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_crucible_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// Legacy: ExecuteTask for backward compatibility
type CrucibleTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrucibleTaskRequest) Reset() {
	*x = CrucibleTaskRequest{}
	mi := &file_proto_crucible_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrucibleTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrucibleTaskRequest) ProtoMessage() {}

func (x *CrucibleTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrucibleTaskRequest.ProtoReflect.Descriptor instead.
func (*CrucibleTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{8}
}

func (x *CrucibleTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CrucibleTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CrucibleTaskRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CrucibleTaskRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CrucibleTaskRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CrucibleTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Attestation   string                 `protobuf:"bytes,3,opt,name=attestation,proto3" json:"attestation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrucibleTaskResponse) Reset() {
	*x = CrucibleTaskResponse{}
	mi := &file_proto_crucible_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrucibleTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrucibleTaskResponse) ProtoMessage() {}

func (x *CrucibleTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crucible_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrucibleTaskResponse.ProtoReflect.Descriptor instead.
func (*CrucibleTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_crucible_proto_rawDescGZIP(), []int{9}
}

func (x *CrucibleTaskResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CrucibleTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CrucibleTaskResponse) GetAttestation() string {
	if x != nil {
		return x.Attestation
	}
	return ""
}

var File_proto_crucible_proto protoreflect.FileDescriptor

const file_proto_crucible_proto_rawDesc = "" +
	"\n" +
	"\x14proto/crucible.proto\x12\x17vaos.kernel.crucible.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x01\n" +
	"\x14CreateSandboxRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\x12\x1f\n" +
	"\vintent_hash\x18\x03 \x01(\tR\n" +
	"intentHash\x12?\n" +
	"\x06limits\x18\x04 \x01(\v2'.vaos.kernel.crucible.v1.ResourceLimitsR\x06limits\"p\n" +
	"\x15CreateSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x19\n" +
	"\bpty_path\x18\x02 \x01(\tR\aptyPath\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"q\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\x7f\n" +
	"\x0fExecuteResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"C\n" +
	"\x10TerminateRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\"s\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12'\n" +
	"\x0fnetwork_enabled\x18\x03 \x01(\bR\x0enetworkEnabled\"C\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03jwt\x18\x02 \x01(\tR\x03jwt\"F\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\x03R\blastSeen\"\x97\x02\n" +
	"\x13CrucibleTaskRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\\\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2<.vaos.kernel.crucible.v1.CrucibleTaskRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x14CrucibleTaskResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vattestation\x18\x03 \x01(\tR\vattestation2\x89\x04\n" +
	"\x0eSandboxControl\x12n\n" +
	"\rCreateSandbox\x12-.vaos.kernel.crucible.v1.CreateSandboxRequest\x1a..vaos.kernel.crucible.v1.CreateSandboxResponse\x12`\n" +
	"\vExecuteCode\x12'.vaos.kernel.crucible.v1.ExecuteRequest\x1a(.vaos.kernel.crucible.v1.ExecuteResponse\x12U\n" +
	"\x10TerminateSandbox\x12).vaos.kernel.crucible.v1.TerminateRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\tHeartbeat\x12).vaos.kernel.crucible.v1.HeartbeatRequest\x1a*.vaos.kernel.crucible.v1.HeartbeatResponse\x12j\n" +
	"\vExecuteTask\x12,.vaos.kernel.crucible.v1.CrucibleTaskRequest\x1a-.vaos.kernel.crucible.v1.CrucibleTaskResponseB*Z(vaos-kernel/internal/grpc/gen/cruciblev1b\x06proto3"

var (
	file_proto_crucible_proto_rawDescOnce sync.Once
	file_proto_crucible_proto_rawDescData []byte
)

func file_proto_crucible_proto_rawDescGZIP() []byte {
	file_proto_crucible_proto_rawDescOnce.Do(func() {
		file_proto_crucible_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crucible_proto_rawDesc), len(file_proto_crucible_proto_rawDesc)))
	})
	return file_proto_crucible_proto_rawDescData
}

var file_proto_crucible_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_crucible_proto_goTypes = []any{
	(*CreateSandboxRequest)(nil),  // 0: vaos.kernel.crucible.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil), // 1: vaos.kernel.crucible.v1.CreateSandboxResponse
	(*ExecuteRequest)(nil),        // 2: vaos.kernel.crucible.v1.ExecuteRequest
	(*ExecuteResponse)(nil),       // 3: vaos.kernel.crucible.v1.ExecuteResponse
	(*TerminateRequest)(nil),      // 4: vaos.kernel.crucible.v1.TerminateRequest
	(*ResourceLimits)(nil),        // 5: vaos.kernel.crucible.v1.ResourceLimits
	(*HeartbeatRequest)(nil),      // 6: vaos.kernel.crucible.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 7: vaos.kernel.crucible.v1.HeartbeatResponse
	(*CrucibleTaskRequest)(nil),   // 8: vaos.kernel.crucible.v1.CrucibleTaskRequest
	(*CrucibleTaskResponse)(nil),  // 9: vaos.kernel.crucible.v1.CrucibleTaskResponse
	nil,                           // 10: vaos.kernel.crucible.v1.CrucibleTaskRequest.ParametersEntry
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_proto_crucible_proto_depIdxs = []int32{
	5,  // 0: vaos.kernel.crucible.v1.CreateSandboxRequest.limits:type_name -> vaos.kernel.crucible.v1.ResourceLimits
	10, // 1: vaos.kernel.crucible.v1.CrucibleTaskRequest.parameters:type_name -> vaos.kernel.crucible.v1.CrucibleTaskRequest.ParametersEntry
	0,  // 2: vaos.kernel.crucible.v1.SandboxControl.CreateSandbox:input_type -> vaos.kernel.crucible.v1.CreateSandboxRequest
	2,  // 3: vaos.kernel.crucible.v1.SandboxControl.ExecuteCode:input_type -> vaos.kernel.crucible.v1.ExecuteRequest
	4,  // 4: vaos.kernel.crucible.v1.SandboxControl.TerminateSandbox:input_type -> vaos.kernel.crucible.v1.TerminateRequest
	6,  // 5: vaos.kernel.crucible.v1.SandboxControl.Heartbeat:input_type -> vaos.kernel.crucible.v1.HeartbeatRequest
	8,  // 6: vaos.kernel.crucible.v1.SandboxControl.ExecuteTask:input_type -> vaos.kernel.crucible.v1.CrucibleTaskRequest
	1,  // 7: vaos.kernel.crucible.v1.SandboxControl.CreateSandbox:output_type -> vaos.kernel.crucible.v1.CreateSandboxResponse
	3,  // 8: vaos.kernel.crucible.v1.SandboxControl.ExecuteCode:output_type -> vaos.kernel.crucible.v1.ExecuteResponse
	11, // 9: vaos.kernel.crucible.v1.SandboxControl.TerminateSandbox:output_type -> google.protobuf.Empty
	7,  // 10: vaos.kernel.crucible.v1.SandboxControl.Heartbeat:output_type -> vaos.kernel.crucible.v1.HeartbeatResponse
	9,  // 11: vaos.kernel.crucible.v1.SandboxControl.ExecuteTask:output_type -> vaos.kernel.crucible.v1.CrucibleTaskResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_crucible_proto_init() }
func file_proto_crucible_proto_init() {
	if File_proto_crucible_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crucible_proto_rawDesc), len(file_proto_crucible_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crucible_proto_goTypes,
		DependencyIndexes: file_proto_crucible_proto_depIdxs,
		MessageInfos:      file_proto_crucible_proto_msgTypes,
	}.Build()
	File_proto_crucible_proto = out.File
	file_proto_crucible_proto_goTypes = nil
	file_proto_crucible_proto_depIdxs = nil
}
