// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: proto/interface.proto

package interfacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterfaceDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceDispatchRequest) Reset() {
	*x = InterfaceDispatchRequest{}
	mi := &file_proto_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceDispatchRequest) ProtoMessage() {}

func (x *InterfaceDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceDispatchRequest.ProtoReflect.Descriptor instead.
func (*InterfaceDispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_interface_proto_rawDescGZIP(), []int{0}
}

func (x *InterfaceDispatchRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InterfaceDispatchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InterfaceDispatchRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InterfaceDispatchRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *InterfaceDispatchRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type InterfaceDispatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RenderedOutput string                 `protobuf:"bytes,3,opt,name=rendered_output,json=renderedOutput,proto3" json:"rendered_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterfaceDispatchResponse) Reset() {
	*x = InterfaceDispatchResponse{}
	mi := &file_proto_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceDispatchResponse) ProtoMessage() {}

func (x *InterfaceDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceDispatchResponse.ProtoReflect.Descriptor instead.
func (*InterfaceDispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_interface_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceDispatchResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *InterfaceDispatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InterfaceDispatchResponse) GetRenderedOutput() string {
	if x != nil {
		return x.RenderedOutput
	}
	return ""
}

var File_proto_interface_proto protoreflect.FileDescriptor

const file_proto_interface_proto_rawDesc = "" +
	"\n" +
	"\x15proto/interface.proto\x12\x18vaos.kernel.interface.v1\"\xa2\x02\n" +
	"\x18InterfaceDispatchRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12b\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2B.vaos.kernel.interface.v1.InterfaceDispatchRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x19InterfaceDispatchResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0frendered_output\x18\x03 \x01(\tR\x0erenderedOutput2\x87\x01\n" +
	"\x10InterfaceService\x12s\n" +
	"\bDispatch\x122.vaos.kernel.interface.v1.InterfaceDispatchRequest\x1a3.vaos.kernel.interface.v1.InterfaceDispatchResponseB+Z)vaos-kernel/internal/grpc/gen/interfacev1b\x06proto3"

var (
	file_proto_interface_proto_rawDescOnce sync.Once
	file_proto_interface_proto_rawDescData []byte
)

func file_proto_interface_proto_rawDescGZIP() []byte {
	file_proto_interface_proto_rawDescOnce.Do(func() {
		file_proto_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interface_proto_rawDesc), len(file_proto_interface_proto_rawDesc)))
	})
	return file_proto_interface_proto_rawDescData
}

var file_proto_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_interface_proto_goTypes = []any{
	(*InterfaceDispatchRequest)(nil),  // 0: vaos.kernel.interface.v1.InterfaceDispatchRequest
	(*InterfaceDispatchResponse)(nil), // 1: vaos.kernel.interface.v1.InterfaceDispatchResponse
	nil,                               // 2: vaos.kernel.interface.v1.InterfaceDispatchRequest.ParametersEntry
}
var file_proto_interface_proto_depIdxs = []int32{
	2, // 0: vaos.kernel.interface.v1.InterfaceDispatchRequest.parameters:type_name -> vaos.kernel.interface.v1.InterfaceDispatchRequest.ParametersEntry
	0, // 1: vaos.kernel.interface.v1.InterfaceService.Dispatch:input_type -> vaos.kernel.interface.v1.InterfaceDispatchRequest
	1, // 2: vaos.kernel.interface.v1.InterfaceService.Dispatch:output_type -> vaos.kernel.interface.v1.InterfaceDispatchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_interface_proto_init() }
func file_proto_interface_proto_init() {
	if File_proto_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interface_proto_rawDesc), len(file_proto_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_interface_proto_goTypes,
		DependencyIndexes: file_proto_interface_proto_depIdxs,
		MessageInfos:      file_proto_interface_proto_msgTypes,
	}.Build()
	File_proto_interface_proto = out.File
	file_proto_interface_proto_goTypes = nil
	file_proto_interface_proto_depIdxs = nil
}
