// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.0
// source: proto/swarm.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelService_RequestToken_FullMethodName     = "/vaos.kernel.KernelService/RequestToken"
	KernelService_SubmitTelemetry_FullMethodName  = "/vaos.kernel.KernelService/SubmitTelemetry"
	KernelService_SubmitRoutingLog_FullMethodName = "/vaos.kernel.KernelService/SubmitRoutingLog"
	KernelService_ConfirmAudit_FullMethodName     = "/vaos.kernel.KernelService/ConfirmAudit"
	KernelService_ExecuteIntent_FullMethodName    = "/vaos.kernel.KernelService/ExecuteIntent"
)

// KernelServiceClient is the client API for KernelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Kernel Service for VAS-Swarm communication
type KernelServiceClient interface {
	// Request a JWT token for an agent action
	RequestToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// Submit telemetry data from agent
	SubmitTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
	// Submit routing logs from Signal Theory classifier
	SubmitRoutingLog(ctx context.Context, in *RoutingLogRequest, opts ...grpc.CallOption) (*RoutingLogResponse, error)
	// Confirm ALCOA+ audit trail
	ConfirmAudit(ctx context.Context, in *AuditConfirmation, opts ...grpc.CallOption) (*AuditResponse, error)
	// Execute intent (legacy for backward compatibility)
	ExecuteIntent(ctx context.Context, in *SwarmIntentRequest, opts ...grpc.CallOption) (*SwarmIntentResponse, error)
}

type kernelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelServiceClient(cc grpc.ClientConnInterface) KernelServiceClient {
	return &kernelServiceClient{cc}
}

func (c *kernelServiceClient) RequestToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, KernelService_RequestToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) SubmitTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, KernelService_SubmitTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) SubmitRoutingLog(ctx context.Context, in *RoutingLogRequest, opts ...grpc.CallOption) (*RoutingLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutingLogResponse)
	err := c.cc.Invoke(ctx, KernelService_SubmitRoutingLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ConfirmAudit(ctx context.Context, in *AuditConfirmation, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, KernelService_ConfirmAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ExecuteIntent(ctx context.Context, in *SwarmIntentRequest, opts ...grpc.CallOption) (*SwarmIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwarmIntentResponse)
	err := c.cc.Invoke(ctx, KernelService_ExecuteIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelServiceServer is the server API for KernelService service.
// All implementations must embed UnimplementedKernelServiceServer
// for forward compatibility.
//
// Kernel Service for VAS-Swarm communication
type KernelServiceServer interface {
	// Request a JWT token for an agent action
	RequestToken(context.Context, *TokenRequest) (*TokenResponse, error)
	// Submit telemetry data from agent
	SubmitTelemetry(context.Context, *TelemetryRequest) (*TelemetryResponse, error)
	// Submit routing logs from Signal Theory classifier
	SubmitRoutingLog(context.Context, *RoutingLogRequest) (*RoutingLogResponse, error)
	// Confirm ALCOA+ audit trail
	ConfirmAudit(context.Context, *AuditConfirmation) (*AuditResponse, error)
	// Execute intent (legacy for backward compatibility)
	ExecuteIntent(context.Context, *SwarmIntentRequest) (*SwarmIntentResponse, error)
	mustEmbedUnimplementedKernelServiceServer()
}

// UnimplementedKernelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelServiceServer struct{}

func (UnimplementedKernelServiceServer) RequestToken(context.Context, *TokenRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestToken not implemented")
}
func (UnimplementedKernelServiceServer) SubmitTelemetry(context.Context, *TelemetryRequest) (*TelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTelemetry not implemented")
}
func (UnimplementedKernelServiceServer) SubmitRoutingLog(context.Context, *RoutingLogRequest) (*RoutingLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRoutingLog not implemented")
}
func (UnimplementedKernelServiceServer) ConfirmAudit(context.Context, *AuditConfirmation) (*AuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmAudit not implemented")
}
func (UnimplementedKernelServiceServer) ExecuteIntent(context.Context, *SwarmIntentRequest) (*SwarmIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteIntent not implemented")
}
func (UnimplementedKernelServiceServer) mustEmbedUnimplementedKernelServiceServer() {}
func (UnimplementedKernelServiceServer) testEmbeddedByValue()                       {}

// UnsafeKernelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServiceServer will
// result in compilation errors.
type UnsafeKernelServiceServer interface {
	mustEmbedUnimplementedKernelServiceServer()
}

func RegisterKernelServiceServer(s grpc.ServiceRegistrar, srv KernelServiceServer) {
	// If the following call panics, it indicates UnimplementedKernelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelService_ServiceDesc, srv)
}

func _KernelService_RequestToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).RequestToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_RequestToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).RequestToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_SubmitTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).SubmitTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_SubmitTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).SubmitTelemetry(ctx, req.(*TelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_SubmitRoutingLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutingLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).SubmitRoutingLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_SubmitRoutingLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).SubmitRoutingLog(ctx, req.(*RoutingLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ConfirmAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditConfirmation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ConfirmAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ConfirmAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ConfirmAudit(ctx, req.(*AuditConfirmation))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ExecuteIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwarmIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ExecuteIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ExecuteIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ExecuteIntent(ctx, req.(*SwarmIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelService_ServiceDesc is the grpc.ServiceDesc for KernelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vaos.kernel.KernelService",
	HandlerType: (*KernelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestToken",
			Handler:    _KernelService_RequestToken_Handler,
		},
		{
			MethodName: "SubmitTelemetry",
			Handler:    _KernelService_SubmitTelemetry_Handler,
		},
		{
			MethodName: "SubmitRoutingLog",
			Handler:    _KernelService_SubmitRoutingLog_Handler,
		},
		{
			MethodName: "ConfirmAudit",
			Handler:    _KernelService_ConfirmAudit_Handler,
		},
		{
			MethodName: "ExecuteIntent",
			Handler:    _KernelService_ExecuteIntent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/swarm.proto",
}
