// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: proto/swarm.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request a JWT token for an action
type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                              // Agent making the request
	IntentHash    string                 `protobuf:"bytes,2,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`                                                     // SHA256 hash of the intent
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`                                                     // Type of action (build, execute, etc.)
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_proto_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TokenRequest) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

func (x *TokenRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *TokenRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response with JWT token
type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                           // JWT token
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`                           // Token scope
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                           // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Submit telemetry data
type TelemetryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Agent status
	Status      string  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // idle, busy, error
	CpuUsage    float32 `protobuf:"fixed32,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage float32 `protobuf:"fixed32,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	// Performance metrics
	TasksCompleted  int32   `protobuf:"varint,6,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	TasksFailed     int32   `protobuf:"varint,7,opt,name=tasks_failed,json=tasksFailed,proto3" json:"tasks_failed,omitempty"`
	AvgTaskDuration float32 `protobuf:"fixed32,8,opt,name=avg_task_duration,json=avgTaskDuration,proto3" json:"avg_task_duration,omitempty"` // seconds
	// LLM usage
	TokensUsed   int32   `protobuf:"varint,9,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	CostEstimate float32 `protobuf:"fixed32,10,opt,name=cost_estimate,json=costEstimate,proto3" json:"cost_estimate,omitempty"`
	// Additional metrics
	CustomMetrics map[string]string `protobuf:"bytes,11,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TelemetryRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *TelemetryRequest) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *TelemetryRequest) GetTasksCompleted() int32 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *TelemetryRequest) GetTasksFailed() int32 {
	if x != nil {
		return x.TasksFailed
	}
	return 0
}

func (x *TelemetryRequest) GetAvgTaskDuration() float32 {
	if x != nil {
		return x.AvgTaskDuration
	}
	return 0
}

func (x *TelemetryRequest) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *TelemetryRequest) GetCostEstimate() float32 {
	if x != nil {
		return x.CostEstimate
	}
	return 0
}

func (x *TelemetryRequest) GetCustomMetrics() map[string]string {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

// Response to telemetry submission
type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_proto_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Submit routing logs from Signal Theory classifier
type RoutingLogRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId   string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Signal Theory 5-tuple
	Mode       string  `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`             // BUILD, EXECUTE, ANALYZE, MAINTAIN, ASSIST
	Genre      string  `protobuf:"bytes,5,opt,name=genre,proto3" json:"genre,omitempty"`           // DIRECT, INFORM, COMMIT, DECIDE, EXPRESS
	Type       string  `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`             // question, request, issue, etc.
	Format     string  `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`         // message, command, document, etc.
	Weight     float32 `protobuf:"fixed32,8,opt,name=weight,proto3" json:"weight,omitempty"`       // 0.0 to 1.0
	Confidence string  `protobuf:"bytes,9,opt,name=confidence,proto3" json:"confidence,omitempty"` // high, medium, low
	// Routing decision
	Tier          string `protobuf:"bytes,10,opt,name=tier,proto3" json:"tier,omitempty"` // elite, specialist, utility
	Model         string `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string `protobuf:"bytes,12,opt,name=provider,proto3" json:"provider,omitempty"`
	IntentHash    string `protobuf:"bytes,13,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"` // SHA256 hash of the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingLogRequest) Reset() {
	*x = RoutingLogRequest{}
	mi := &file_proto_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingLogRequest) ProtoMessage() {}

func (x *RoutingLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingLogRequest.ProtoReflect.Descriptor instead.
func (*RoutingLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *RoutingLogRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoutingLogRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RoutingLogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RoutingLogRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RoutingLogRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *RoutingLogRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RoutingLogRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RoutingLogRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RoutingLogRequest) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *RoutingLogRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *RoutingLogRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RoutingLogRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RoutingLogRequest) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

// Response to routing log submission
type RoutingLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // ID for tracking this routing decision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingLogResponse) Reset() {
	*x = RoutingLogResponse{}
	mi := &file_proto_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingLogResponse) ProtoMessage() {}

func (x *RoutingLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingLogResponse.ProtoReflect.Descriptor instead.
func (*RoutingLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *RoutingLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoutingLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RoutingLogResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// ALCOA+ audit confirmation
type AuditConfirmation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentId    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActionId   string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	IntentHash string                 `protobuf:"bytes,3,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`
	JwtToken   string                 `protobuf:"bytes,4,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	// ALCOA+ attributes
	Attributable    bool `protobuf:"varint,5,opt,name=attributable,proto3" json:"attributable,omitempty"`
	Legible         bool `protobuf:"varint,6,opt,name=legible,proto3" json:"legible,omitempty"`
	Contemporaneous bool `protobuf:"varint,7,opt,name=contemporaneous,proto3" json:"contemporaneous,omitempty"`
	Original        bool `protobuf:"varint,8,opt,name=original,proto3" json:"original,omitempty"`
	Accurate        bool `protobuf:"varint,9,opt,name=accurate,proto3" json:"accurate,omitempty"`
	// Additional compliance metadata
	PerformedAt   int64             `protobuf:"varint,10,opt,name=performed_at,json=performedAt,proto3" json:"performed_at,omitempty"`
	PerformedBy   string            `protobuf:"bytes,11,opt,name=performed_by,json=performedBy,proto3" json:"performed_by,omitempty"`
	Method        string            `protobuf:"bytes,12,opt,name=method,proto3" json:"method,omitempty"`
	Context       map[string]string `protobuf:"bytes,13,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditConfirmation) Reset() {
	*x = AuditConfirmation{}
	mi := &file_proto_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditConfirmation) ProtoMessage() {}

func (x *AuditConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditConfirmation.ProtoReflect.Descriptor instead.
func (*AuditConfirmation) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *AuditConfirmation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuditConfirmation) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *AuditConfirmation) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

func (x *AuditConfirmation) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *AuditConfirmation) GetAttributable() bool {
	if x != nil {
		return x.Attributable
	}
	return false
}

func (x *AuditConfirmation) GetLegible() bool {
	if x != nil {
		return x.Legible
	}
	return false
}

func (x *AuditConfirmation) GetContemporaneous() bool {
	if x != nil {
		return x.Contemporaneous
	}
	return false
}

func (x *AuditConfirmation) GetOriginal() bool {
	if x != nil {
		return x.Original
	}
	return false
}

func (x *AuditConfirmation) GetAccurate() bool {
	if x != nil {
		return x.Accurate
	}
	return false
}

func (x *AuditConfirmation) GetPerformedAt() int64 {
	if x != nil {
		return x.PerformedAt
	}
	return 0
}

func (x *AuditConfirmation) GetPerformedBy() string {
	if x != nil {
		return x.PerformedBy
	}
	return ""
}

func (x *AuditConfirmation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditConfirmation) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Response to audit confirmation
type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	AuditId       string                 `protobuf:"bytes,2,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_proto_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *AuditResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *AuditResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *AuditResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Legacy: Swarm intent execution (backward compatibility)
type SwarmIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmIntentRequest) Reset() {
	*x = SwarmIntentRequest{}
	mi := &file_proto_swarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmIntentRequest) ProtoMessage() {}

func (x *SwarmIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmIntentRequest.ProtoReflect.Descriptor instead.
func (*SwarmIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{8}
}

func (x *SwarmIntentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SwarmIntentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SwarmIntentRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SwarmIntentRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *SwarmIntentRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type SwarmIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmIntentResponse) Reset() {
	*x = SwarmIntentResponse{}
	mi := &file_proto_swarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmIntentResponse) ProtoMessage() {}

func (x *SwarmIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmIntentResponse.ProtoReflect.Descriptor instead.
func (*SwarmIntentResponse) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{9}
}

func (x *SwarmIntentResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SwarmIntentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SwarmIntentResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_proto_swarm_proto protoreflect.FileDescriptor

const file_proto_swarm_proto_rawDesc = "" +
	"\n" +
	"\x11proto/swarm.proto\x12\vvaos.kernel\"\xed\x01\n" +
	"\fTokenRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vintent_hash\x18\x02 \x01(\tR\n" +
	"intentHash\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.vaos.kernel.TokenRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xfc\x03\n" +
	"\x10TelemetryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x02R\vmemoryUsage\x12'\n" +
	"\x0ftasks_completed\x18\x06 \x01(\x05R\x0etasksCompleted\x12!\n" +
	"\ftasks_failed\x18\a \x01(\x05R\vtasksFailed\x12*\n" +
	"\x11avg_task_duration\x18\b \x01(\x02R\x0favgTaskDuration\x12\x1f\n" +
	"\vtokens_used\x18\t \x01(\x05R\n" +
	"tokensUsed\x12#\n" +
	"\rcost_estimate\x18\n" +
	" \x01(\x02R\fcostEstimate\x12W\n" +
	"\x0ecustom_metrics\x18\v \x03(\v20.vaos.kernel.TelemetryRequest.CustomMetricsEntryR\rcustomMetrics\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe0\x02\n" +
	"\x11RoutingLogRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x14\n" +
	"\x05genre\x18\x05 \x01(\tR\x05genre\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x16\n" +
	"\x06weight\x18\b \x01(\x02R\x06weight\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\tR\n" +
	"confidence\x12\x12\n" +
	"\x04tier\x18\n" +
	" \x01(\tR\x04tier\x12\x14\n" +
	"\x05model\x18\v \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\f \x01(\tR\bprovider\x12\x1f\n" +
	"\vintent_hash\x18\r \x01(\tR\n" +
	"intentHash\"o\n" +
	"\x12RoutingLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\x8a\x04\n" +
	"\x11AuditConfirmation\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12\x1f\n" +
	"\vintent_hash\x18\x03 \x01(\tR\n" +
	"intentHash\x12\x1b\n" +
	"\tjwt_token\x18\x04 \x01(\tR\bjwtToken\x12\"\n" +
	"\fattributable\x18\x05 \x01(\bR\fattributable\x12\x18\n" +
	"\alegible\x18\x06 \x01(\bR\alegible\x12(\n" +
	"\x0fcontemporaneous\x18\a \x01(\bR\x0fcontemporaneous\x12\x1a\n" +
	"\boriginal\x18\b \x01(\bR\boriginal\x12\x1a\n" +
	"\baccurate\x18\t \x01(\bR\baccurate\x12!\n" +
	"\fperformed_at\x18\n" +
	" \x01(\x03R\vperformedAt\x12!\n" +
	"\fperformed_by\x18\v \x01(\tR\vperformedBy\x12\x16\n" +
	"\x06method\x18\f \x01(\tR\x06method\x12E\n" +
	"\acontext\x18\r \x03(\v2+.vaos.kernel.AuditConfirmation.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\rAuditResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed\x12\x19\n" +
	"\baudit_id\x18\x02 \x01(\tR\aauditId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x89\x02\n" +
	"\x12SwarmIntentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12O\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2/.vaos.kernel.SwarmIntentRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x13SwarmIntentResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail2\x9d\x03\n" +
	"\rKernelService\x12E\n" +
	"\fRequestToken\x12\x19.vaos.kernel.TokenRequest\x1a\x1a.vaos.kernel.TokenResponse\x12P\n" +
	"\x0fSubmitTelemetry\x12\x1d.vaos.kernel.TelemetryRequest\x1a\x1e.vaos.kernel.TelemetryResponse\x12S\n" +
	"\x10SubmitRoutingLog\x12\x1e.vaos.kernel.RoutingLogRequest\x1a\x1f.vaos.kernel.RoutingLogResponse\x12J\n" +
	"\fConfirmAudit\x12\x1e.vaos.kernel.AuditConfirmation\x1a\x1a.vaos.kernel.AuditResponse\x12R\n" +
	"\rExecuteIntent\x12\x1f.vaos.kernel.SwarmIntentRequest\x1a .vaos.kernel.SwarmIntentResponseB!Z\x1fgithub.com/vaos/kernel/pkg/grpcb\x06proto3"

var (
	file_proto_swarm_proto_rawDescOnce sync.Once
	file_proto_swarm_proto_rawDescData []byte
)

func file_proto_swarm_proto_rawDescGZIP() []byte {
	file_proto_swarm_proto_rawDescOnce.Do(func() {
		file_proto_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_swarm_proto_rawDesc), len(file_proto_swarm_proto_rawDesc)))
	})
	return file_proto_swarm_proto_rawDescData
}

var file_proto_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_swarm_proto_goTypes = []any{
	(*TokenRequest)(nil),        // 0: vaos.kernel.TokenRequest
	(*TokenResponse)(nil),       // 1: vaos.kernel.TokenResponse
	(*TelemetryRequest)(nil),    // 2: vaos.kernel.TelemetryRequest
	(*TelemetryResponse)(nil),   // 3: vaos.kernel.TelemetryResponse
	(*RoutingLogRequest)(nil),   // 4: vaos.kernel.RoutingLogRequest
	(*RoutingLogResponse)(nil),  // 5: vaos.kernel.RoutingLogResponse
	(*AuditConfirmation)(nil),   // 6: vaos.kernel.AuditConfirmation
	(*AuditResponse)(nil),       // 7: vaos.kernel.AuditResponse
	(*SwarmIntentRequest)(nil),  // 8: vaos.kernel.SwarmIntentRequest
	(*SwarmIntentResponse)(nil), // 9: vaos.kernel.SwarmIntentResponse
	nil,                         // 10: vaos.kernel.TokenRequest.MetadataEntry
	nil,                         // 11: vaos.kernel.TelemetryRequest.CustomMetricsEntry
	nil,                         // 12: vaos.kernel.AuditConfirmation.ContextEntry
	nil,                         // 13: vaos.kernel.SwarmIntentRequest.ParametersEntry
}
var file_proto_swarm_proto_depIdxs = []int32{
	10, // 0: vaos.kernel.TokenRequest.metadata:type_name -> vaos.kernel.TokenRequest.MetadataEntry
	11, // 1: vaos.kernel.TelemetryRequest.custom_metrics:type_name -> vaos.kernel.TelemetryRequest.CustomMetricsEntry
	12, // 2: vaos.kernel.AuditConfirmation.context:type_name -> vaos.kernel.AuditConfirmation.ContextEntry
	13, // 3: vaos.kernel.SwarmIntentRequest.parameters:type_name -> vaos.kernel.SwarmIntentRequest.ParametersEntry
	0,  // 4: vaos.kernel.KernelService.RequestToken:input_type -> vaos.kernel.TokenRequest
	2,  // 5: vaos.kernel.KernelService.SubmitTelemetry:input_type -> vaos.kernel.TelemetryRequest
	4,  // 6: vaos.kernel.KernelService.SubmitRoutingLog:input_type -> vaos.kernel.RoutingLogRequest
	6,  // 7: vaos.kernel.KernelService.ConfirmAudit:input_type -> vaos.kernel.AuditConfirmation
	8,  // 8: vaos.kernel.KernelService.ExecuteIntent:input_type -> vaos.kernel.SwarmIntentRequest
	1,  // 9: vaos.kernel.KernelService.RequestToken:output_type -> vaos.kernel.TokenResponse
	3,  // 10: vaos.kernel.KernelService.SubmitTelemetry:output_type -> vaos.kernel.TelemetryResponse
	5,  // 11: vaos.kernel.KernelService.SubmitRoutingLog:output_type -> vaos.kernel.RoutingLogResponse
	7,  // 12: vaos.kernel.KernelService.ConfirmAudit:output_type -> vaos.kernel.AuditResponse
	9,  // 13: vaos.kernel.KernelService.ExecuteIntent:output_type -> vaos.kernel.SwarmIntentResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_swarm_proto_init() }
func file_proto_swarm_proto_init() {
	if File_proto_swarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_swarm_proto_rawDesc), len(file_proto_swarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_swarm_proto_goTypes,
		DependencyIndexes: file_proto_swarm_proto_depIdxs,
		MessageInfos:      file_proto_swarm_proto_msgTypes,
	}.Build()
	File_proto_swarm_proto = out.File
	file_proto_swarm_proto_goTypes = nil
	file_proto_swarm_proto_depIdxs = nil
}
